### PR TITLE
spaces mess with interactive browsing

### PR DESCRIPTION
**Pull request by tmrhombus**
please?

### CODE REVIEW

**Comment by aehart** [comment]
How exactly do the spaces mess with interactive browsing? Can you give more details?

**Comment by tmrhombus** [comment]
For example:

root [0] 
Attaching file hist.root as _file0...
(TFile *) 0x2ad31b0
root [1] .ls
TFile**		hist.root	
 TFile*		hist.root	
  KEY: TDirectoryFile	ZControlRegionCutFlowPlotter;1	ZControlRegionCutFlowPlotter
  KEY: TDirectoryFile	ZControlRegionPlotter;1	ZControlRegionPlotter
root [2] ZControlRegionPlotter->cd();
root [3] .ls
TDirectoryFile*		ZControlRegionPlotter	ZControlRegionPlotter
 KEY: TDirectoryFile	Muon Plots;1	Muon Plots
 KEY: TDirectoryFile	Muon-muon Plots;1	Muon-muon Plots
 KEY: TDirectoryFile	Muon-beamspot Plots;1	Muon-beamspot Plots
 KEY: TDirectoryFile	Jet Plots;1	Jet Plots
 KEY: TDirectoryFile	Muon-jet-beamspot Plots;1	Muon-jet-beamspot Plots
 KEY: TDirectoryFile	Met Plots;1	Met Plots
 KEY: TDirectoryFile	Muon-met Plots;1	Muon-met Plots


Then trying to do something like Jet Plots->cd(); doesn't work because of the space. Tab completion is also broken here.

**Comment by aehart** [comment]
I would have supported this change when the framework was initially developed, but unfortunately, by now, we have so much code that expects the space in the directory names that it would be a real pain to migrate everything. Not to mention that we currently have a lot of output on disk with spaces in the directory names.

So, others should weigh in as well, but I don't think we should merge this change.

You can however get around your problem using gDirectory:
`root [0] 
Attaching file /data/users/hart/condor/2016_final_prompt/signalAcceptance_DEFGH_v2/AMSB_chargino_700GeV_100cm_80X.root as _file0...
(TFile *) 0x51ee450
root [1] .ls
TFile**		/data/users/hart/condor/2016_final_prompt/signalAcceptance_DEFGH_v2/AMSB_chargino_700GeV_100cm_80X.root	
 TFile*		/data/users/hart/condor/2016_final_prompt/signalAcceptance_DEFGH_v2/AMSB_chargino_700GeV_100cm_80X.root	
  KEY: TDirectoryFile	DisTrkSelectionCutFlowPlotter;1	DisTrkSelectionCutFlowPlotter
  KEY: TDirectoryFile	DisTrkSelectionPlotter;1	DisTrkSelectionPlotter
  KEY: TDirectoryFile	disTrkSelectionSmearedJetsCutFlowPlotter;1	disTrkSelectionSmearedJetsCutFlowPlotter
  KEY: TDirectoryFile	disTrkSelectionSmearedJetsPlotter;1	disTrkSelectionSmearedJetsPlotter
root [2] DisTrkSelectionPlotter->cd ();
root [3] .ls
TDirectoryFile*		DisTrkSelectionPlotter	DisTrkSelectionPlotter
 KEY: TDirectoryFile	Track Plots;1	Track Plots
 KEY: TDirectoryFile	Track-beamspot Plots;1	Track-beamspot Plots
 KEY: TDirectoryFile	Track-eventvariable Plots;1	Track-eventvariable Plots
 KEY: TDirectoryFile	Met Plots;1	Met Plots
 KEY: TDirectoryFile	Met-eventvariable Plots;1	Met-eventvariable Plots
 KEY: TDirectoryFile	Jet Plots;1	Jet Plots
 KEY: TDirectoryFile	Eventvariable Plots;1	Eventvariable Plots
 KEY: TDirectoryFile	Track-met Plots;1	Track-met Plots
root [4] gDirectory->cd ("Jet Plots");
root [5] .ls
TDirectoryFile*		Jet Plots	Jet Plots
 KEY: TH1D	numJets;1	Number of Selected Jets
 KEY: TH1D	jetPt;1	Jet Transverse Momentum
 KEY: TH1D	jetEta;1	Jet Eta
 KEY: TH1D	jetPhi;1	Jet Phi
 KEY: TH1D	jetCharge;1	Jet Charge
 KEY: TH1D	jetMass;1	Jet Mass
 KEY: TH2D	jetEtaPhi;1	Jet Eta vs. Jet Phi
 KEY: TH1D	jetChargedHadronEnergyFraction;1	Jet Charged Hadron Fraction
 KEY: TH1D	jetNeutralHadronEnergyFraction;1	Jet Neutral Hadron Fraction
 KEY: TH1D	jetNeutralEMEnergyFraction;1	Jet Neutral EM Fraction
 KEY: TH1D	jetChargedEMEnergyFraction;1	Jet Charged EM Fraction
 KEY: TH1D	jetCSV;1	Jet Combined Secondary Vertex B-tagging Discriminant
 KEY: TH1D	jetPileUpId;1	Jet PileUp Id`

**Comment by tmrhombus** [comment]
fair enough

**Comment by lantone** [comment]
Yeah, sorry Tom, for better or worse there's ~5 years * ~10 people worth of inertia in the framework at this point.  But another workaround is to just open a TBrowser, that's my to-go way of looking at the plots.

**Comment by tmrhombus** [comment]
no problem, it was just a small convenience. gDirectory->cd() is basically equivalent and from my poking around i think i can agree this framework looks pretty well established(:

**Pull request closed without merging**
