### PR TITLE
Add uniqueMotherPdgId to Mcparticle

### PR DESCRIPTION
**Pull request by btcardwell**
Add uniqueMotherPdgId to Mcparticle following the implementation in HardInteractionMcparticle. This works as expected when tested in 10_2_12.

### CODE REVIEW

**Comment by jalimena** [comment]
also, it would be good if @bpf6qc  can also take a look and give his 2 cents

**Comment by btcardwell** [comment]
Hey, we actually don't need to add anything to genMatchable because the object we get back when using genMatchable is an Mcparticle. It looks like `genMatchedParticle.noFlags.uniqueMotherPdgId` gives us exactly what we want.

**Comment by jalimena** [comment]
excellent. @bpf6qc , ok to merge then?

**Comment by bpf6qc** [comment]
This is okay to merge for me, and yes genMatchable provides a reference to this object so no more modifications are needed.

From a style perspective:
```
if(!uniqueMother(mcpart)) continue;
mcpart.set_uniqueMotherPdgId(uniqueMother(mcpart)->pdgId());
```
is a bit inefficient for two reasons. Firstly calling `uniqueMother` twice is looping again, and secondly the `continue` could be a trap if someone ever adds code below this in the same brackets. It's not _that_ bad, I'm torn on mentioning it or not. I'll leave it to others' opinion.

Otherwise go ahead and merge this.

**Comment by btcardwell** [comment]
Not a bad point on the style issue. I haven't tested it, but would something like the following address both your concerns?

`const reco::Candidate *uniqueMother = uniqueMother(mcpart);`
`if (uniqueMother(mcpart)) mcpart.set_uniqueMotherPdgId(uniqueMother->pdgId());`

**Comment by bpf6qc** [comment]
@btcardwell yes exactly. There might be the same code in HardInteractionMcparticle too, maybe it's a good chance to change this.

**Comment by jalimena** [comment]
ok cool, agreed. I'd ask @btcardwell to make this change for both mcparticles and hardInteractionmcparticles.

**Comment by btcardwell** [comment]
Alright, I changed mcparticle and hardinteractionmcparticle and tested again. If everyone's on board, I believe this should be good to go.

**Comment by bpf6qc** [comment]
Looks good by me, thanks for the change.

**Comment by jalimena** [comment]
+1

**Pull request merged**
