### PR TITLE
changes to over/underflow

### PR DESCRIPTION
**Pull request by jalimena**
with option to turn it off, as in makePlots.py

### CODE REVIEW

**Comment by btcardwell** [comment]
This looks like a good idea and the plots look good. Are `lowLimit` and `uppLimit` used anywhere?

**Comment by jalimena** [comment]
Thanks, @btcardwell ! re low/uppLimit, I had missed a part in the makePlots.py code. Now fixed. (This matters for the integral of histograms, so it wouldn't have shown up in my test plots above.)

**Comment by jalimena** [comment]
Come to think of it, I think we want to do the same for makeEfficiencyPlots (before we divide the histograms), so my latest commit does that.

**Review by bpfrancis — APPROVED** [review]
The changes are uncontroversial, this looks good. There are two questions I want to raise, but neither are problems for me and are a matter of the group's tastes. I'll approve this PR and pose them to see how people feel:

1. I'm not sure what the default should be, to show the over/underflows or not. Generally I don't show them, but as long as users know what's happening they can see the flag to turn this on/off.

2. The on/off flag controls both the visual display of over/underflow, but also the numerical treatment of them in integral plots. I would think they should always be included in integral plots (doing the right thing with left/right directions), and be a choice to show or not in the non-integrated histograms.

**Comment by bpfrancis** [comment]
Actually a third:

3. This groups overflow with underflow. Most plots will never see underflow, like your PT examples, but perhaps it's worth separating flags in case someone's surprised. I could see disTrks using -999 for "no selected jet" and wanting to turn off the spike at zero.

**Comment by jalimena** [comment]
Thanks, @bpfrancis .

Regarding your points:
1. I think we should be consistent with what is done in makePlots.py, which by default plots them.
2. Ok sounds good, I will change this here (and also in makePlots.py if it's the same there, haven't yet looked).
3. This is a good point and one we should also do for makePlots.

So I'll make the changes regarding 2 and 3 above asap. Please wait for those before merging.

**Comment by jalimena** [comment]
New PR summary:
- change makeComparisonPlots to plot over/underflow by default, and also for makeEfficiencyPlots (before dividing histograms)
- change to always include under&overflow in integral histograms, in makeComparisonPlots and makePlots
- split option to turn off under&overflow plotting (noOverUnderFlow option) into two options: noOverFlow and noUnderFlow, for makePlots, makeComparisonPlots, and makeEfficiencyPlots

**Comment by jalimena** [comment]
ah sorry, i meant to be clearer: it would be great if you two could have another look now

**Comment by bpfrancis** [comment]
My three comments have been addressed very nicely, thanks @jalimena . I still approve, perhaps @btcardwell can look and merge.

**Comment by btcardwell** [comment]
Yes, everything looks good to me. I'll go ahead and merge.

**Pull request merged**
