### PR TITLE
Add automatic sanity check for cut and histogram definitions

### PR DESCRIPTION
**Pull request by btcardwell**
Add check to add_channels that raises an exception if any cuts or histograms have invalid attributes. This protects against typos like `IndexX` or `numberrequired` that currently pass silently.

### CODE REVIEW

**Comment by jalimena** [comment]
+1
highly support. i can't think now of any other checks we could make. i leave it to @bpf6qc  to merge, if he's happy.

**Comment by btcardwell** [comment]
I should add that this has been tested and works as expected in 10_2_X for all DisplacedSUSY cuts and hists.

**Comment by bpf6qc** [comment]
I think this is a good idea, but I balk at the PSet defaults and built-ins, the ones beginning with `_`, since there may be CMSSW updates or Python built-ins that show up. I'd like to see only the 'regular' attributes checked, and anything beginning with `_` ignored in this.

**Comment by btcardwell** [comment]
Good point @bpf6qc. I've pushed another commit to ignore attributes starting with `_`.

**Comment by bpf6qc** [comment]
Thanks for the change @btcardwell, this looks good to merge for me.

**Pull request merged**
