### PR TITLE
Lifetime reweighting fixes and debugging help

### PR DESCRIPTION
**Pull request by jalimena**
This PR has some fixes for Displaced SUSY lifetime reweighting:
- it adds the non-default reweighting rules for Displaced SUSY samples in configurationOptions.py
- it fixes the string conversion of type 0.1 to 0p1
- it adds options to deal with special Displaced SUSY pythia generation of stops to R-hadrons to final stops

and also adds some lifetime reweighting help in general:
- it adds a script to check if lifetime reweighting rules in configurationOptions.py are right
- it adds a hack in LifetimeWeightProducer_cff in order to run LifetimeWeightProducer interactively

This PR has been tested in 10_2_X. The lifetime reweighting event variables in the trees now look right - see some plots of the tree variables for stopToLB1000_10mm attached.
eventvariable_lifetimeWeight
eventvariable_lifetimeWeight_1000006_1cmTo1cm
eventvariable_lifetimeWeight_1000006_1cmTo0p9cm
eventvariable_lifetimeWeight_1000006_1cmTo0p8cm
eventvariable_lifetimeWeight_1000006_1cmTo0p5cm
eventvariable_lifetimeWeight_1000006_1cmTo0p2cm

### CODE REVIEW

**Comment by jalimena** [comment]
added a boolean to turn on/off the histogram weighting, default True (on) - a fix for Disappearing Tracks histograms

**Comment by jalimena** [comment]
I think my last commit fixes the case when we reweight to 0.001 cm, because the script output is now: 
```
Rules for sample: stopToLB1000_0p1mm
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.002]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.003]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.004]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.005]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.006]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.007]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.008]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.009]
	Is default rule: False
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.01]
	Is default rule: True
	******
	PDG IDs: [1000006]
	CTaus: [0.01] --> [0.001]
	Is default rule: False
```

However, i'm checking it now with the trees, so please wait for that check before merging.

**Comment by jalimena** [comment]
Ok, looks right:
Screen Shot 2020-12-04 at 4 50 53 PM

And I confirmed with another sample that I didn't screw up anything else in the process.

I believe this PR is good to be merged, from my side.

**Comment by btcardwell** [comment]
This all looks good from my perspective, though I expect both @bpfrancis and @jalimena understand the details better than me. Assuming @jalimena's tests keep going well, I vote @bpfrancis merges whenever he's satisfied.

**Comment by jalimena** [comment]
sigh, don't merge yet. i've now plotted the cutflow, and there's clearly something wrong with the normalization. if anyone sees anything wrong like that in this PR, please point me to it.

**Comment by jalimena** [comment]
ok, ignore the last comment, it was a mistake on my end! everything is fine with the PR, as far as i know

**Comment by jalimena** [comment]
ping

**Review by bpfrancis — APPROVED** [review]
This looks good to me; the disappearing tracks use case is preserved and the displaced SUSY case is fixed it seems. So, nice work @jalimena, thanks.

**Pull request merged**
