### PR TITLE
add DY to tautau to forced leptonic decay sample

### PR DESCRIPTION
**Pull request by jalimena**
This PR should be pretty simple, but the one thing I'm not positive of is the cross section. Additional help would be appreciated.

### CODE REVIEW

**Comment by btcardwell** [comment]
Your commit looks good to me. I unfortunately don't think I have any valuable insight on the cross section.

**Comment by jalimena** [comment]
cross section is now more reasonable, see the elog in the comment. 

can we merge this PR now? We've been using it for about 2 weeks.

**Comment by jalimena** [comment]
ok, thanks, @bpf6qc .

@btcardwell , anything to add, or can we merge?

**Comment by btcardwell** [comment]
Nothing to add on my end. I'll go ahead and merge!

**Pull request merged**
