### PR TITLE
Add 2017v2, 2018 electron SFs

### PR DESCRIPTION
**Pull request by bpf6qc**
https://twiki.cern.ch/twiki/bin/view/CMS/EgammaIDRecipesRun2

Electron SFs are always pretty straightforward. There's a V2 that appeared for 2017 since last we looked, and I've added them with a version/wp suffix "V2". The veto ID is missing from 2017v2 and 2018 but there's not much we can do about that.

Lastly the changes to recreateLeptonSFs.C compete with PR #110 so we will need to merge them.

### CODE REVIEW

**Comment by jalimena** [comment]
hi @bpf6qc  - what you've implemented here looks good to me. however, does this PR deal with all the issues we mentioned in https://github.com/OSU-CMS/OSUT3Analysis/issues/87 ? Probably not, right?

**Comment by bpf6qc** [comment]
@jalimena no it doesn't, although I'm looking at that now. #87 is just as important as this PR so perhaps I should fold it into this one.

**Comment by jalimena** [comment]
so now that the muon SF PR is merged, do you want to rebase and then we merge this one? or we wait until you add the info in #87?

**Comment by bpf6qc** [comment]
I've rebased this PR with PR #110, and instead of waiting to merge these I've created a separate PR #113 .

**Comment by bpf6qc** [comment]
@jalimena yes these two PRs are now pretty disjoint in their effects. I'll merge this now, thanks!

**Pull request merged**
