### PR TITLE
Update lifetime reweighting rules for sleptons samples

### PR DESCRIPTION
**Pull request by btcardwell**
A small update to the lifetime reweighting rules for the GMSB interpretation of the Displaced Leptons analysis. Sorry to have all these recent PRs that are just small changes to configurationOptions.

### CODE REVIEW

**Comment by jalimena** [comment]
hey @btcardwell , so this PR reweights the 1000mm samples up to 10,000mm, is that right? You've checked that this is kosher for the number of events we have?

**Comment by btcardwell** [comment]
Yes, this will reweight the 1,000mm samples up to 10,000mm. We don't have the stats to do this reliably yet, but we should have them soon.

Also, I imagine onfigurationOptions could evolve a bit more as we complete these final samples -- maybe we could keep this PR open for a bit and use it as a catch-all "configurationOptions updates" PR?

**Comment by jalimena** [comment]
yeah sounds good

**Comment by jalimena** [comment]
we are preparing a new PR that adds additional lifetime things on top of this PR, so merging this one now

**Review by jalimena — APPROVED** [review]

**Pull request merged**
