### PR TITLE
Allow use of remote skim directories

### PR DESCRIPTION
**Pull request by bpf6qc**
e.g.:
osusub.py -t OSUT3Ntuple -l localConfig_2017_Tau.py -w testSubmission
-P -J R_Golden17 -s
"root://cmsxrootd-site.fnal.gov//store/user/lpclonglived/DisappTrks/skim
/2017/tauTagSkim" -a TauTagSkim

Will need extensive testing and review.

### CODE REVIEW

**Comment by bpf6qc** [comment]
A test submission can be found in:
/data/users/bfrancis/condor/testSubmission/

These jobs ran successfully although I made a mistake and didn't pull in my recent tau PR, so no events pass. But datasetInfo config file can be seen and files were opened.

**Comment by bpf6qc** [comment]
Important note: xrootd will only give you access to /store, so accessing the condor work directories won't be possible. The osusub.py script also needs access to existing skims' datasetInfo_*_cfg.py file which is in the condor work directory.

For the example given (TauTagSkim) I manually copied datasetInfo_*_cfg.py from each working directory to the appropriate skim directory on the LPC. Something should be modified to place this file there, but existing skims will need to have this done manually.

**Comment by jalimena** [comment]
I fear I won't have a chance to test this as soon as I would like, so I've added @btcardwell  as a reviewer, in case he has time to look before I do.

**Comment by btcardwell** [comment]
A test submission with passing events in data and MC can be found here:

/data/users/bcardwell/condor/testRemoteSkimPR

100% of jobs finished successfully, the merge went well, and the resulting plots look reasonable.

**Comment by jalimena** [comment]
seems sufficient to me. unless you have another test in mind, @bpf6qc ?

**Comment by bpf6qc** [comment]
I'd like one more fix in this PR which I'm testing now, for running at the LPC.

**Comment by btcardwell** [comment]
Tests of running at the LPC over skims hosted in LPC eos appear successful. I did two different tests using 2017 data and MC with slightly different osusub -s arguments. Both worked, but the latter of the two listed below is the use case we will actually want when working at the LPC.

The osusub lines for each test are listed below.

osusub.py -t OSUT3Ntuple -l PreselectionOptions.py -w EEPreselectionSkim_2017Analysis_24July2018 -P -J R_Golden17 -s root://cmsxrootd-site.fnal.gov//store/user/lpclonglived/DisplacedLeptons/EEInitialSkim_2017Analysis_19July2018 -a EESkim -H /eos/uscms/store/group/lpclonglived/DisplacedLeptons

osusub.py -t OSUT3Ntuple -l PreselectionOptions.py -w EEPreselection_2017Analysis_24July2018 -P -J R_Golden17 -s EEInitialSkim_2017Analysis_19July2018 -a EESkim -H /eos/uscms/store/group/lpclonglived/DisplacedLeptons

In both cases, 100% of jobs finished successfully, the merge went well, and the resulting plots look reasonable.

**Comment by btcardwell** [comment]
I think these tests should be sufficient. I'm going to go ahead and merge

**Pull request merged**
