### PR TITLE
improvements for makeEfficiencyPlot.py and makeComparisonPlots.py

### PR DESCRIPTION
**Pull request by jalimena**
makeEfficiencyPlot.py and makeComparisonPlots.py need a facelift. This PR:

- Adds the option addOneToRatio, so you can plot data/MC as in makePlots.py
- improves the cosmetics of the plot, as done in makePlots.py

### CODE REVIEW

**Comment by jalimena** [comment]
oh, forgot to say, works fine in 10_2_12

**Comment by btcardwell** [comment]
This all looks reasonable to me. If @jalimena has tested, I'd vote to merge.

**Comment by jalimena** [comment]
indeed i have tested it in 10_2, both updated scripts are fine

**Comment by jalimena** [comment]
@bpf6qc , any comment? or can we merge this relatively straightforward PR?

**Comment by jalimena** [comment]
ping?

**Comment by bpf6qc** [comment]
@jalimena I've been buried in T3 trials this week, sorry! This looked quite reasonable to me, and is a purely plot/graphics based script so bug risks are low. I would be interested to see a before/after comparison of the outputs, but consider this an endorsement from me now.

**Comment by jalimena** [comment]
Well, it's not a perfect comparison because I used different options in these two sets of plots, but it gives the idea:

"before": https://milliqanelog.asc.ohio-state.edu:8080/DisplacedSUSY/1403
"after" : https://milliqanelog.asc.ohio-state.edu:8080/DisplacedSUSY/1649

Thanks a lot for taking a look, despite being busy!

**Comment by btcardwell** [comment]
All sounds good. I'll merge now.

**Pull request merged**
